name: Build and publish to Chrome Webstore

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present

      # Package the build output into a zip file
      - name: Package extension
        run: zip -r extension.zip build

      # Publish the extension to the Chrome Web Store
      - name: Publish to Chrome Web Store
        uses: nwtgck/actions-chrome-webstore@v1
        with:
          client_id: ${{ secrets.CHROME_WEBSTORE_CLIENT_ID }}
          client_secret: ${{ secrets.CHROME_WEBSTORE_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CHROME_WEBSTORE_REFRESH_TOKEN }}
          extension_id: ${{ secrets.CHROME_WEBSTORE_EXTENSION_ID }}
          zip_file: extension.zip
