name: Build and publish to Chrome Webstore

on:
  push:
    branches: ["main", "prerelease"]
  pull_request:
    branches: ["main", "prerelease"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run build --if-present

      # Package the build output into a zip file with a date-based name.
      - name: Package extension
        id: package
        run: |
          mkdir -p artifacts
          ZIP_FILE="$(date +'%Y-%m-%d')_tj-volume-mixer.zip"
          cd build && zip -r "../artifacts/${ZIP_FILE}" . && cd ..
          echo "zip_file=artifacts/${ZIP_FILE}" >> $GITHUB_OUTPUT
          echo "artifact_name=${ZIP_FILE}" >> $GITHUB_OUTPUT

      - name: Upload build zip file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.artifact_name }}
          path: ${{ steps.package.outputs.zip_file }}
          retention-days: 1

      # Publish the extension to the Chrome Web Store (only on push to main).
      - name: Upload to Chrome Web Store
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: "upload" # or "publish" if you prefer
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          extension_id: ${{ secrets.EXTENSION_ID }}
          zip_file: ${{ steps.package.outputs.zip_file }}
